### ISSUE TITLE
Settings window can't be moved; Gammy closes upon closing the settings window

### ISSUE THREAD

**Issue by logix2** [Fushko/gammy#1]
Using Ubuntu 19.04 (with Gnome Shell): the Gammy (built from Git) settings window can't be moved. Also, closing the settings window, Gammy is closed (shouldn't it only close the settings window?).

**Comment by Fushko** [comment]
>Using Ubuntu 19.04 (with Gnome Shell): the Gammy (built from Git) settings window can't be moved.

Strange. I'm on Pop_os 19.04, which is based on Ubuntu and also using Gnome. I can move the window just fine. 

Try building without the Qt::FramelessWindowHint flag [here](https://github.com/Fushko/gammy/blob/1c7b3b6b76ab2a43506e7c097b7b5229a302c679/src/mainwindow.cpp#L37).

> Also, closing the settings window, Gammy is closed (shouldn't it only close the settings window?).

That's intended. X quits the program, _ minimizes it. The way I see it, pressing the X should always terminate a program.

**Comment by logix2** [comment]
> Try building without the Qt::FramelessWindowHint flag here.

That fixes it, thanks!

> That's intended. X quits the program, _ minimizes it. The way I see it, pressing the X should always terminate a program.

No other app that I know of (at least on Linux) works like that. Because users expect for the settings window to close, not the whole app...

**Comment by Fushko** [comment]
>No other app that I know of (at least on Linux) works like that. Because users expect for the settings window to close, not the whole app...

You're not wrong. The window has Win32 style minimize/close buttons, because that's where I come from.
Thing is, when I want to close an app, if I have the settings window open I tend to close it first (out of habit), then click on the tray icon, then click on quit. That's three clicks. Instead I can just close it directly from the settings with one click here. 
Besides, the settings window could also be seen as the main window in my case, because there isn't any other for now.

**Comment by yellowcrash10** [comment]
Your application appears to be a tray/indicator applet rather than a regular program, and I would expect such a program to remain running when closing the configuration window.

**Comment by Fushko** [comment]
I think I might just end up removing that flag, killing two birds with one stone. It's fine for windows but I guess custom windows aren't really practical on Linux, with all the different DEs and such.

**Comment by Fushko** [comment]
Commit https://github.com/Fushko/gammy/commit/fab3aa6387f492028fd3bae2c12cf9f3ed106cd1 on dev should address both of these issues.

**Comment by logix2** [comment]
Great, thanks!
