### ISSUE TITLE
gammy crashes immediately after start

### ISSUE THREAD

**Issue by YantCaccia** [Fushko/gammy#10]
on Windows 10 (latest Insider preview fast ring build 19002), dependencies installed, gammy crashes in about 1\2 seconds within the start. No matter if app is launched as or as not the administrator. I'm basically unable to use it. No error is displayed in any way. Gammy is in the tray, 1 2 there's no more.

**Comment by Fushko** [comment]
Hey, could you please try this debug executable:

[gammy v.0.9.52-debug.zip](https://github.com/Fushko/gammy/files/3775886/gammy.v.0.9.52-debug.zip)

and see what gets printed in the console? Thank you.

**Comment by YantCaccia** [comment]
> Hey, could you please try this debug executable:
> 
> [gammy v.0.9.52-debug.zip](https://github.com/Fushko/gammy/files/3775886/gammy.v.0.9.52-debug.zip)
> 
> and see what gets printed in the console? Thank you.

![Annotazione 2019-10-27 170633](https://user-images.githubusercontent.com/11892754/67637589-32c86c00-f8dc-11e9-913e-00efc6e5d50d.jpg)

Nothing is different.. Console appears (screenshot taken) then it force closes in seconds together with gammy in the tray

**Comment by Fushko** [comment]
Seems like DXGI is initialized fine, so it’s probably something in the screenshot process or when reading the image buffer. There is no error message to work with so i’ll improve my logging and get back to this.

**Comment by YantCaccia** [comment]
Keep up the work man💪! If i can help in any way reach me, looking forward to use your app 😉

**Comment by Fushko** [comment]
I just published a [new version](https://github.com/Fushko/gammy/releases) with much improved logging.

If you would like to help me troubleshoot, follow these steps:
- Replace the contents of gammysettings.cfg (located in the .exe directory) with the following:
```
minBrightness=255
maxBrightness=255
offset=0
temp=0
speed=3
threshold=32
updateRate=500
auto=0
toggleLimit=0
debug=6
```
- Run gammy.exe
- If it doesn't crash, click on the tray icon and check Auto brightness in the settings window
- If it doesn't crash still, lower the "Min brightness" as much as possible
- Upload the contents of gammylog.txt (also in the .exe directory)

**Comment by YantCaccia** [comment]
The latest build works great!

A few things I think you should work on:

- I tried the latest 3 builds (today's included) and Windows keeps telling me the archive is 'not valid'. So I opened them with 7zip that told me it was impossibile to open the file as .zip and it was opening it as .rar instead (at least it succeeds);

- Gammy should keep record when Night Brightness is on and adjust its behaviour: IMHO offset should be increased by 10 to 20% (but it may be just my personal flavour);

- Increase the range of possible selectable speed parameter.

I just tweaked around for 15min I think so the log is hugely big and still growing. Do you want me to upload it whatever? Or, if you prefer, I can simply have another fresh log (dunno if it is still useful).
Let me know and congrats for the good work!

**Comment by Fushko** [comment]
> The latest build works great! 

I don't know what I did to fix it, but I'm glad it works! 

>I tried the latest 3 builds (today's included) and Windows keeps telling me the archive is 'not valid'. So I opened them with 7zip that told me it was impossibile to open the file as .zip and it was opening it as .rar instead (at least it succeeds);

Thanks for the heads-up! I packed the folder with RAR and changed the extension to .zip to make it compatible with Github. I didn't realize that was bad practice. I'll proceed to zip the files with 7zip and replace them asap.

> Gammy should keep record when Night Brightness is on and adjust its behaviour: IMHO offset should be increased by 10 to 20% (but it may be just my personal flavour);

You mean an option to increase the offset as color temperature decreases? Not a bad idea if I understood well, since lower temperatures also have a natural dimming effect. I'll keep it in mind. 

> I just tweaked around for 15min I think so the log is hugely big and still growing. Do you want me to upload it whatever? Or, if you prefer, I can simply have another fresh log (dunno if it is still useful).

Don't worry, the log has a limit of 3 MB and a max of 3 files, it won't fill up your drive :laughing: 

You can delete the log files and turn debug down to 5 in gammysettings.cfg.
If you see any logs starting with ERROR or WARN I'd be interested in seeing them. Otherwise you can just disable them completely by changing it to 0.

**Comment by YantCaccia** [comment]
> You mean an option to increase the offset as color temperature decreases?

Yes! I noticed that when my PC switch from Night Light OFF to Night Light ON with Gammy open and working I need to manually increase Windows' brightness by 2 steps, or increase Gammy "offset" parameter by 15/20%.

It could be useful to implement a function to let Gammy recognize Night Light is turning ON and automatically increase the "offset" parameter by an amount chosen by the user.

> If you see any logs starting with ERROR or WARN I'd be interested in seeing them.

I will run Gammy with debug = 5 for a few days and if I see something like you mentioned I will post here.

However good job and keep it up m8!
