### ISSUE TITLE
Gammy tray/startup.

### ISSUE THREAD

**Issue by kajlando** [Fushko/gammy#101]
Would it be possible to add another application that would be just an app tray?
Or:
An in-app option to automatically boot on start to tray.
Or:
gammy-tray command for the terminal.

**Comment by Fushko** [comment]
> Would it be possible to add another application that would be just an app tray?

Probably yes, but that would imply bringing everything that's currently in the window to the tray, and I don't wanna go that route for now.

> An in-app option to automatically boot on start to tray.

I'll implement that at some point for linux. The major DEs allow you to autostart apps easily so it was never really a priority.
