### ISSUE TITLE
"Temperature: Auto" slows down OS/framerate.

### ISSUE THREAD

**Issue by kajlando** [Fushko/gammy#102]
When I turn on "Auto" in "Temperature" it slows down my OS/framerate in stable and development version as well.
I'm using Garuda Linux with GNOME.

**Comment by kajlando** [comment]
Never mind. It happen but actually when I changed the temperature and clicked auto again it wasn't slowing down my OS anymore.

**Comment by kajlando** [comment]
It actually happens when changing the temperature with auto. It's temporary but I had actually a situation when it was slowing 'till I didn't checked and unchecked "Temeprature" auto"

**Comment by kajlando** [comment]
I reopen this issue again..
I had problems with the "Auto" option on Garuda Linux and now also on Manjaro.
It basically makes my OS sluggish unless I turn it off.
It might be the option "Adaption zone" that's doing it.

**Comment by Fushko** [comment]
> It might be the option "Adaptation time" that's doing it.

Care to elaborate? Does it happen only on certain values? Which ones?

You can try lowering `temp_fps` in `~/.config/gammyconf`. The default value is too high for slow temperature changes and I'll probably lower it in a future release.

**Comment by kajlando** [comment]
Changing "temp_fps": 45, " to "temp_fps": 1, " fixed it.
However this happens with the default "temp_fps": 45, ":
So there's an adaptation time which slowly adjusts the temperature and while doing so gammy slows my OS. 
For example if you set the adaptation time to 60 minutes it will be adapting in these 60 minutes and while doing so slowing down the frame rate.
This also happens when you move the slider.
--
