### ISSUE TITLE
Clicking on system tray icon does not restore Gammy window if it is minimised

### ISSUE THREAD

**Issue by Gitoffthelawn** [Fushko/gammy#104]
When Gammy is minimised, clicking on the system tray icon does not restore Gammy's window.  It should! :)

Tested with Gammy v0.9.64 on Win7.

**Comment by Fushko** [comment]
On Win 7, this happens to me when I click too fast (and there's nothing I can do about that). Otherwise it works all the time.

**Comment by Gitoffthelawn** [comment]
Hmm... I'm not following you... what do you mean by "click too fast"?  I'm referring to simple clicking, as opposed to double-clicking.  (Although double-clicking has the same issue for me.)

**Comment by Fushko** [comment]
I'm also referring to simple clicking. It works everytime for me. Perhaps you're saying that the window doesn't get drawn above others? That's a different issue, in that case.
