### ISSUE TITLE
Gammy opens the settings window by default.

### ISSUE THREAD

**Issue by RazuvaevDD** [Fushko/gammy#107]
Gammy opens the settings window by default, and this is inconvenient. Is it possible to open a window only by clicking on the tray icon? (Arch Linux, Awesome WM)

**Comment by Fushko** [comment]
> Is it possible to open a window only by clicking on the tray icon?

Read the usage instructions in the README.

> Gammy opens the settings window by default, and this is inconvenient.

Refer to the pinned issue. The tray is probably not detected
