### ISSUE TITLE
How to launch Gammy in background on startup (Ubuntu)

### ISSUE THREAD

**Issue by Pimentoso** [Fushko/gammy#116]
Hello, I use Ubuntu 20.04, I'd like to launch Gammy upon login, but adding it on the "startup applications" list causes the Gammy window to popup every time. Is there any way to run it automatically minimized to tray? Thanks.

**Comment by Fushko** [comment]
You have to give it a delay because of a known issue: https://github.com/Fushko/gammy/issues/57#issuecomment-751358770

You also need to set `wnd_show_on_startup` to `false` in the config (~/.config/gammyconf).
