### ISSUE TITLE
Compilation error: size_t not defined.

### ISSUE THREAD

**Issue by LeSnake04** [Fushko/gammy#118]
src/utils.h:17:29: Fehler: »size_t« wurde nicht deklariert
   17 | double interpTemp(int step, size_t color_ch);
      |                             ^~~~~~
make: *** [Makefile:1027: build/obj/utils.o] Fehler 1
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
error: failed to build 'gammy-git-0.9.64.r3.g6404ca3-1':

**Comment by Fushko** [comment]
Fixed as a silent update. Thanks @pkos98!
