### ISSUE TITLE
compile error X11/Xutil.h

### ISSUE THREAD

**Issue by iconoclasthero** [Fushko/gammy#133]
I had issues getting qmake to look at qt5 instead of qt4 but sorted that out with the [accepted answer](https://askubuntu.com/questions/938422/qmake-is-not-recognized).

```
$ /dev/shm/cache/gammy$ qmake
Info: creating stash file /dev/shm/cache/gammy/.qmake.stash
Project MESSAGE: Qt 5.9.5
Project MESSAGE: Release build
Project MESSAGE: Bin path: /usr/bin
Project MESSAGE: Data path: /usr/share

/dev/shm/cache/gammy$ sudo make install
g++ -c -pipe -O3 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -Iinclude -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/moc -isystem /usr/include/libdrm -Isrc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o build/obj/dspctl-xlib.o src/dspctl-xlib.cpp
src/dspctl-xlib.cpp:6:10: fatal error: X11/Xutil.h: No such file or directory
 #include <X11/Xutil.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:496: recipe for target 'build/obj/dspctl-xlib.o' failed
make: *** [build/obj/dspctl-xlib.o] Error 1

/dev/shm/cache/gammy$ make --version;qmake --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu

/dev/shm/cache/gammy$ which qt5ct; apt show qt5ct
/usr/bin/qt5ct
Package: qt5ct
Version: 0.34-1build2
⋮

/dev/shm/cache/gammy$ ver
No value set for `/apps/metacity/general/theme'
 user@computer
 OS: Ubuntu 18.04 bionic
 Kernel: x86_64 Linux 5.4.0-90-generic
 Uptime: 1d 5h 57m
 Packages: 3650
 Shell: bash 4.4.20
 Resolution: 1600x900
 DE: GNOME 
 WM: Metacity
 GTK Theme: Adwaita-dark [GTK2/3]
 Icon Theme: noia_kde_100
 Font: Ubuntu 9
 CPU: Intel Core i3-4010U @ 4x 1.7GHz
 GPU: Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)
 RAM: 4142MiB / 7650MiB
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
Linux inspiron 5.4.0-90-generic #101~18.04.1-Ubuntu SMP Fri Oct 22 09:25:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by iconoclasthero** [comment]
Ok, it's taken me hours to compile this on Bionic.  You really, _really_ should let people know that in order to do so they need to do a whole bunch of stuff beyond just "sudo apt install build-essential libgl1-mesa-dev libxxf86vm-dev libxext-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools" because you need a backport of Qt 5.15 which is an entire process https://launchpad.net/~savoury1/+archive/ubuntu/qt-5-15

As the PPA maintainer explains, "NOTES FOR ALL: Upgrading the system Qt stack is a major system change as a lot of highly used software depends on Qt (ie. digiKam as one example) and the KDE stack must also be upgraded to a newer version (>= 5.80.0) that is compatible with newer Qt 5.15.x software. So remember to do a full backup first, same as before any such major upgrade! All these PPAs are required for full functionality and installation of the backported Qt/KDE packages:"

I wouldn't even have known that was required if I hadn't seen #12.

> **Qt 5.15.x - backports (Xenial & newer)**
> PPA description
> Backport of Qt 5.15.x stack (and dependencies) for Xenial, Bionic & Focal.
> 
> This PPA also requires compatible KDE 5.80.x backports for any system that has KDE-based software installed. So make sure to read the notes at the KDE 5.80 PPA for latest info about the KDE backports before proceeeding:
> 
> https://launchpad.net/~savoury1/+archive/ubuntu/kde-5-80
> 
> Note (21 Aug 2021): If any dependencies are missing after adding the PPAs described in the install instructions below then make sure to inform me so that the dependencies can be copied here or to the KDE PPA as appropriate.
> 
> *** Install ***
> 
> NOTES FOR ALL: Upgrading the system Qt stack is a major system change as a lot of highly used software depends on Qt (ie. digiKam as one example) and the KDE stack must also be upgraded to a newer version (>= 5.80.0) that is compatible with newer Qt 5.15.x software. So remember to do a full backup first, same as before any such major upgrade! All these PPAs are required for full functionality and installation of the backported Qt/KDE packages:
> 
>   sudo add-apt-repository ppa:savoury1/qt-5-15
>   sudo add-apt-repository ppa:savoury1/kde-5-80
>   sudo add-apt-repository ppa:savoury1/gpg
>   sudo add-apt-repository ppa:savoury1/ffmpeg4
> 
> Also, the VLC 3 PPA is a requirement for Xenial to install Phonon backend for VLC (requires >= 3.0), and recommended for all series. Add like this:
> 
>   sudo add-apt-repository ppa:savoury1/vlc3
> 
> Note for Focal: Core Qt 4 packages of qt4-x11 and qtwebkit are built here allowing Qt 4 (not KDE 4) applications to run on the current latest LTS.
> 
> Notes for Xenial & Bionic: All qt*-opensource-src packages here are built with GCC 9.3.0 and also against ppa:savoury1/display with latest display stack upgrades. These Qt upgrades then require GCC 9.3.0 and the latest display stack to install and run, so add these two PPAs with the commands:
> 
>   sudo add-apt-repository ppa:savoury1/gcc-defaults-9
>   sudo add-apt-repository ppa:savoury1/display
> 
> Notes for Xenial: Some required Qt packages are at ppa:savoury1/qt-xenial which has backports of the Qt 4 & 5 stacks from Bionic. The matching KDE stack from Bionic is also required for proper Qt 4 & KDE 4 support. Also, backported APT/GTK from Bionic is needed for some Qt/KDE backports. So add these four commands at the top of the above list of commands for install:
> 
>   sudo add-apt-repository ppa:savoury1/apt-xenial
>   sudo add-apt-repository ppa:savoury1/gtk-xenial
>   sudo add-apt-repository ppa:savoury1/qt-xenial
>   sudo add-apt-repository ppa:savoury1/kde-xenial
> 
> NOTE FOR ALL: After adding all required PPAs (see above) do these steps:
> 
>   sudo apt-get update
>   sudo apt-get upgrade && sudo apt-get dist-upgrade
> 
> *** Build ***
> 
> This PPA has build dependencies on:
> 
>   ppa:savoury1/build-tools
>   ppa:savoury1/backports
>   ppa:savoury1/python
>   ppa:savoury1/fonts
>   ppa:savoury1/graphics
>   ppa:savoury1/multimedia
>   ppa:savoury1/ffmpeg4
>   ppa:savoury1/vlc3
>   ppa:savoury1/display
>   ppa:savoury1/llvm-defaults-12
>   ppa:savoury1/kde-5-80
> 
> Additionally, for Xenial & Bionic:
> 
>   ppa:savoury1/gcc-defaults-9
>   ppa:savoury1/node-{xenial,bionic}
> 
> Additionally, for Xenial only:
> 
>   ppa:savoury1/apt-xenial
>   ppa:savoury1/perl-xenial
>   ppa:savoury1/gtk-xenial
>   ppa:savoury1/qt-xenial
>   ppa:savoury1/kde-xenial
> 
> *** Credits ***
> 
> - Creators of Qt: Haavard Nord, Eirik Chambe-Eng and the entire Qt team
>   https://wiki.qt.io/About_Qt
> 
> - Package code: Debian Qt/KDE Maintainers
>   https://tracker.debian.org/pkg/qtbase-opensource-src

**Comment by iconoclasthero** [comment]
Ok, now that I've gotten it installed and proceeded to find out how to use it, I see

> Troubleshooting
> Linux
> When building from source, if make fails with PlaceholderText is not a member of QPalette errors in ui_mainwindow.h, the Qt version provided by your distro is older than 5.12. As a workaround you can delete the offending lines in ui_mainwindow.h, then run make again.

Maybe move this up to the section on building it?  Maybe in the "Linux/Building from source" section prior to the Packages subsection?  Maybe throw in a footnote?  Something other than all the way at the bottom after the section on how to use a program that one cannot build without the above or my previous post?

**Comment by Fushko** [comment]
> it's taken me hours to compile this

Such is life for the linux user.

I couldn't be bothered to compile this on ancient Ubuntu versions. Anyway this project won't be worked on anymore, I'm rewriting it from scratch. No Qt this time so compiling will be a breeze even on your ubuntu 2000.

**Comment by iconoclasthero** [comment]
Hey, it compiled fine on my 20.04 machine last night.  I just didn't realize that it would be this much fun.  I like what I've seen so far, but I can't tell if brightness automatically changes with the color/time or how that works?
