### ISSUE TITLE
Enable & Disable by Right Click?

### ISSUE THREAD

**Issue by rayman3003** [Fushko/gammy#16]
I think Its gonna save time, if the gammy has an **On** & **Off** option in the **tray icon**, So we could enable & disable it, just by right clicking & choosing On & Off.

Currently, The only way to disable the gammy, Is to **close** gammy completely!

**Comment by Fushko** [comment]
You mean a switch that toggles automatic adjustments and sets the screen to the default? That's doable, I'll look into it.

**Comment by rayman3003** [comment]
> 
> 
> You mean a switch that toggles automatic adjustments and sets the screen to the default? That's doable, I'll look into it.

Yes. Thank u.

**Comment by Anrock** [comment]
Would be really nice to have this. I've just encountered horrible mouse lag in steam games (probably #54, but not sure) when gammy is active, so quick toggle would be really convenient in case I want to play something.

**Comment by Fushko** [comment]
This feature is now available by performing a middle click on the tray icon.

> Would be really nice to have this. I've just encountered horrible mouse lag in steam games (probably #54, but not sure) when gammy is active, so quick toggle would be really convenient in case I want to play something.

Lag when playing games should be gone too. It's really cool that you can use auto brightness on CSGO to reduce the flashbang blinding effect :grin:

**Comment by rayman3003** [comment]
Thank u very much. ◕‿↼
