### ISSUE TITLE
Failed to start Gammy (Invalid gamma ramp size)

### ISSUE THREAD

**Issue by riteme** [Fushko/gammy#20]
Hello,

I tried to build Gammy on Ubuntu 18.04 (KDE Plasma) following the instructions in README, but Gammy crashes on startup:

```
2020-02-10 18:59:30.940 INFO  [27483] [getConfigPath@146] Config path: /home/riteme/.config/gammy
2020-02-10 18:59:30.940 WARN  [27483] [read@96] Config empty. Creating one.
2020-02-10 18:59:30.940 INFO  [27483] [getConfigPath@146] Config path: /home/riteme/.config/gammy
2020-02-10 18:59:30.940 DEBUG [27483] [save@73] Settings saved
2020-02-10 18:59:30.941 FATAL [27483] [X11::X11@61] Invalid gamma ramp size
```

Here is my system information:

```
Operating System: KDE neon 5.17
KDE Plasma Version: 5.17.4
KDE Frameworks Version: 5.65.0
Qt Version: 5.13.2
Kernel Version: 5.0.0-37-generic
OS Type: 64-bit
```

**Comment by Fushko** [comment]
Hi,
- Could you change "log_lvl" to 6 in /home/riteme/.config/gammy and paste the log output again?
- What's your GPU and screen resolution?
- Are you using Wayland or X11? (Wayland is not supported at the moment)

**Comment by riteme** [comment]
I'm using X11 and my laptop has Intel/NVIDIA dual graphics cards. NVIDIA propriety driver is disabled by `nvidia-prime`. Only the builtin monitor (1920x1080) is in use.

I found that it might be a common issue with `XF86VidModeGetGammaRamp` reporting zero Gamma ramp size: <https://github.com/psychopy/psychopy/issues/2061>

So I followed the instructions in <https://github.com/psychopy/psychopy/issues/2061#issuecomment-428792028> to create `/etc/X11/xorg.conf.d/20-intel.conf` and reboot, and then Gammy works fine.

**Comment by Fushko** [comment]
Fantastic. I'll add these instructions in the readme.
