### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by 7--** [Fushko/gammy#21]
$ make
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Iincludes -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ires/tmp -isystem /usr/include/libdrm -Ires -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o res/tmp/main.o src/main.cpp
src/main.cpp: In function ‘void adjustTemperature(convar&, MainWindow&)’:
src/main.cpp:49:23: error: ‘chrono_literals’ is not a namespace-name
  using namespace std::chrono_literals;
                       ^~~~~~~~~~~~~~~
src/main.cpp:49:38: error: expected namespace-name before ‘;’ token
  using namespace std::chrono_literals;
                                      ^
src/main.cpp: In lambda function:
src/main.cpp:134:51: error: unable to find numeric literal operator ‘operator""s’
     clock_cv.wait_until(lk, system_clock::now() + 60s, [&] { return w.quit; });
                                                   ^~~
src/main.cpp: In function ‘void adjustTemperature(convar&, MainWindow&)’:
src/main.cpp:267:14: error: unable to find numeric literal operator ‘operator""ms’
    sleep_for(50ms);
              ^~~~
src/main.cpp: In function ‘void adjustBrightness(Args&, MainWindow&)’:
src/main.cpp:357:7: warning: ‘if constexpr’ only available with -std=c++1z or -std=gnu++1z
    if constexpr (os == OS::Windows) {
       ^~~~~~~~~
src/main.cpp: In function ‘void recordScreen(Args&, convar&, MainWindow&)’:
src/main.cpp:483:22: error: missing template arguments before ‘lock’
      std::lock_guard lock (args.br_mtx);
                      ^~~~
src/main.cpp: In function ‘int main(int, char**)’:
src/main.cpp:597:5: warning: ‘if constexpr’ only available with -std=c++1z or -std=gnu++1z
  if constexpr (os == OS::Windows) {
     ^~~~~~~~~
Makefile:473: recipe for target 'res/tmp/main.o' failed
make: *** [res/tmp/main.o] Error 1

**Comment by Fushko** [comment]
>X only available with -std=c++1z or -std=gnu++1z

Your compiler doesn't have C++17 support. To update g++, follow these steps (assuming you are using apt package manager): https://tuxamito.com/wiki/index.php/Installing_newer_GCC_versions_in_Ubuntu

To check your version of the g++ compiler, execute `g++ -v` on the terminal. The last line should tell you.
For reference, my g++ version is 9.2.1.

**Comment by JannyJunky** [comment]
i still have this problem
$ make
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Iincludes -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ires/tmp -isystem /usr/include/libdrm -Isrc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o res/tmp/main.o src/main.cpp
src/main.cpp: In function ‘void adjustTemperature(convar&, MainWindow&)’:
src/main.cpp:42:23: error: ‘chrono_literals’ is not a namespace-name
  using namespace std::chrono_literals;
                       ^~~~~~~~~~~~~~~
src/main.cpp:42:38: error: expected namespace-name before ‘;’ token
  using namespace std::chrono_literals;
                                      ^
src/main.cpp: In lambda function:
src/main.cpp:94:51: error: unable to find numeric literal operator ‘operator""s’
     clock_cv.wait_until(lk, system_clock::now() + 60s, [&] { return w.quit; });
                                                   ^~~
src/main.cpp: In function ‘void adjustBrightness(Args&, MainWindow&)’:
src/main.cpp:246:17: error: ‘clamp’ is not a member of ‘std’
   target = std::clamp(target, cfg["min_br"].get<int>(), cfg["max_br"].get<int>());
                 ^~~~~
src/main.cpp: In function ‘void recordScreen(Args&, convar&, MainWindow&)’:
src/main.cpp:393:22: error: missing template arguments before ‘lock’
      std::lock_guard lock (args.br_mtx);
                      ^~~~
src/main.cpp: In function ‘int main(int, char**)’:
src/main.cpp:521:5: warning: ‘if constexpr’ only available with -std=c++1z or -std=gnu++1z
  if constexpr (os == OS::Windows) {
     ^~~~~~~~~
Makefile:489: recipe for target 'res/tmp/main.o' failed
make: *** [res/tmp/main.o] Error 1

**Comment by r-leclair** [comment]
Im getting this:
```
$ make
g++ -c -m64 -pipe -O3 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Iincludes -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ires/tmp -Isrc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o res/tmp/main.o src/main.cpp
src/main.cpp: In function ‘void adjustTemperature(convar&, MainWindow&)’:
src/main.cpp:42:23: error: ‘chrono_literals’ is not a namespace-name
   42 |  using namespace std::chrono_literals;
      |                       ^~~~~~~~~~~~~~~
src/main.cpp: In lambda function:
src/main.cpp:94:51: error: unable to find numeric literal operator ‘operator""s’
   94 |     clock_cv.wait_until(lk, system_clock::now() + 60s, [&] { return w.quit; });
      |                                                   ^~~
src/main.cpp:94:51: note: use ‘-fext-numeric-literals’ to enable more built-in suffixes
src/main.cpp: In function ‘void adjustBrightness(Args&, MainWindow&)’:
src/main.cpp:246:17: error: ‘clamp’ is not a member of ‘std’
  246 |   target = std::clamp(target, cfg["min_br"].get<int>(), cfg["max_br"].get<int>());
      |                 ^~~~~
src/main.cpp: In function ‘void recordScreen(Args&, convar&, MainWindow&)’:
src/main.cpp:393:22: error: missing template arguments before ‘lock’
  393 |      std::lock_guard lock (args.br_mtx);
      |                      ^~~~
src/main.cpp: In function ‘int main(int, char**)’:
src/main.cpp:521:5: warning: ‘if constexpr’ only available with ‘-std=c++17’ or ‘-std=gnu++17’
  521 |  if constexpr (os == OS::Windows) {
      |     ^~~~~~~~~
Makefile:484: recipe for target 'res/tmp/main.o' failed
make: *** [res/tmp/main.o] Error 1
```
using g++ 9.2.1

**Comment by Fushko** [comment]
@JannyJunky @r-leclair I pushed a potential fix. Can you please run the following commands on the app directory:

`git pull` (or edit "c++17" line to "c++1z" in Gammy.pro)
`qmake Gammy.pro`
`make clean`
`make`

**Comment by Fushko** [comment]
Closed for inactivity.
