### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by yochananmarqos** [Fushko/gammy#23]
Manjaro GNOME
gcc 9.2.1 20200130 (Arch Linux 9.2.1+20200130-2)
Qt 5.14.1
Mesa 19.3.4

[Build log](https://pastebin.com/3RmembpX)

**Comment by Fushko** [comment]
This is an issue with Qt 5.14 not present in 5.12.
I added a speculative fix in 0.9.57, please let me know if it still fails.

**Comment by yochananmarqos** [comment]
It build fine with 0.9.57, thanks!
