### ISSUE TITLE
Version checking

### ISSUE THREAD

**Issue by JThundley** [Fushko/gammy#33]
Gammy should support basic command-line options such as --help/-h and --version/-v. It'd also be nice to see what version you have in the gui. As there is no automatic automatic update feature, it's hard to tell if users have the latest version or not.

**Comment by Fushko** [comment]
Added in v0.9.59. Can be seen with `gammy -v` or in the tray.

**Comment by JThundley** [comment]
I just rebuilt Gammy from source for Linux as per the documentation to get the latest version, but I still don't see any command line options. I have no idea which version I actually just built.

**Comment by Fushko** [comment]
> I just rebuilt Gammy from source for Linux as per the documentation to get the latest version, but I still don't see any command line options. I have no idea which version I actually just built.

Hi, the latest version is not released yet (got some bugs to iron out still). You can build it by switching to the develop branch.

**Comment by JThundley** [comment]
Ah that makes sense, I jumped the gun. Thanks again for creating and
working on Gammy, I recommend it to all my peers!
