### ISSUE TITLE
[Gnome] Lag issues when brightness changes

### ISSUE THREAD

**Issue by raduburla** [Fushko/gammy#34]
Hello,

I am experiencing desktop lag when the brightness changes. Increasing adaptation speed and screenshot rate did no help.

Animations and some mouse related tasks like selecting text are laggy.

These are my settings:
![image](https://user-images.githubusercontent.com/25738162/79469216-6d8ba100-7fef-11ea-9dfa-125b2d3f79ef.png)

 I am using a Dell xps 7590 with an i7-9750H and 32GB ram on PopPs 20.04 with Gnome 3.43.3.
Gammy using around 2-3% CPU, Xorg 10-20% CPU when the brightness changes

Any ideas on how I can improve performance or further debug?

**Comment by Fushko** [comment]
You could try tweaking animation framerate. In ~/.config/gammy, lower "brt_fps" (add it if not existent). My config for reference:
```
{
    "auto_br": true,
    "auto_temp": true,
    "brightness": 489,
    "brt_fps": 60,
    "extend_br": false,
    "log_lvl": 5,
    "max_br": 500,
    "min_br": 397,
    "offset": 102,
    "polling_rate": 100,
    "speed": 5,
    "temp_fps": 45,
    "temp_high": 6500,
    "temp_low": 2600,
    "temp_speed": 60.0,
    "temp_state": 0,
    "temp_step": 1,
    "threshold": 14,
    "time_end": "06:00:00",
    "time_start": "18:00:00"
}
```
Apart from that, not much you can do as far as I know. I'd think of GPU/dual-GPU related issues maybe, but it's a stretch. It's definitely strange, I can get the app to run smoothly on Gnome, on a much weaker laptop.

**Comment by volkovpishet** [comment]
Same here. Having lags when brightness changes. Followed your advice and tweaked my gammy settings. Now its better. Don't know really what experience is expected to be, but i am glad to found this issue. Here is my config to reduce lags:
![image](https://user-images.githubusercontent.com/19503244/96508194-44ccb880-126b-11eb-8356-468bcc6d9462.png)

**Comment by Fushko** [comment]
Should be much better now. @raduburla @volkovpishet I would like to know your experience on 0.9.61.

**Comment by raduburla** [comment]
Hi. I can confirm it's much better now :+1: 

Thank you!
