### ISSUE TITLE
Stops working after monitor on/off

### ISSUE THREAD

**Issue by srirams** [Fushko/gammy#35]
The brightness stops adjusting after I switch the monitor off and turn it back on. It seems Gammy tries to adjust the brightness (as in the slider moves) but the brightness doesn't change. Exiting and restarting gammy doesn't help.

**Comment by Fushko** [comment]
My screen settings also reset when i switch the monitor off and on, however they are re-applied as soon as the brightness changes. And even after restarting the app it doesn't work? Which OS are you on?

**Comment by srirams** [comment]
Windows 10 x64... could be an issue with my drivers, because windows 10 "night light" or "f.lux" stop working as well.

Toggling one of the radeon "gpu scaling" or "scaling mode" gets things working again.
