### ISSUE TITLE
Build Broken

### ISSUE THREAD

**Issue by datalot-369** [Fushko/gammy#38]
- MX Linux 19.1

```
make
g++ -c -pipe -O3 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Iincludes -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ires/tmp -isystem /usr/include/libdrm -Isrc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o res/tmp/mainwindow.o src/mainwindow.cpp
In file included from src/mainwindow.cpp:11:
src/ui_mainwindow.h:135:10: error: invalid preprocessing directive #palette
         #palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush8);
          ^~~~~~~
src/ui_mainwindow.h:151:10: error: invalid preprocessing directive #palette
         #palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
          ^~~~~~~
src/ui_mainwindow.h:169:10: error: invalid preprocessing directive #palette
         #palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush8);
          ^~~~~~~
src/ui_mainwindow.h:288:10: error: invalid preprocessing directive #palette1
         #palette1.setBrush(QPalette::Active, QPalette::PlaceholderText, brush8);
          ^~~~~~~~
src/ui_mainwindow.h:304:10: error: invalid preprocessing directive #palette1
         #palette1.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
          ^~~~~~~~
src/ui_mainwindow.h:320:10: error: invalid preprocessing directive #palette1
         #palette1.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush8);
          ^~~~~~~~
In file included from src/mainwindow.cpp:11:
src/ui_mainwindow.h:663:10: error: invalid preprocessing directive #palette2
         #palette2.setBrush(QPalette::Active, QPalette::PlaceholderText, brush8);
          ^~~~~~~~
src/ui_mainwindow.h:679:10: error: invalid preprocessing directive #palette2
         #palette2.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
          ^~~~~~~~
src/ui_mainwindow.h:695:10: error: invalid preprocessing directive #palette2
         #palette2.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush8);
          ^~~~~~~~
make: *** [Makefile:516: res/tmp/mainwindow.o] Error 1
```

I have deleted that lines then...

```
$ make
g++ -c -pipe -O3 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Iincludes -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ires/tmp -isystem /usr/include/libdrm -Isrc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o res/tmp/mainwindow.o src/mainwindow.cpp
g++ -c -pipe -O3 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Iincludes -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ires/tmp -isystem /usr/include/libdrm -Isrc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o res/tmp/utils.o src/utils.cpp
src/utils.cpp: In function ‘double easeInOutQuad(double, double, double, double)’:
src/utils.cpp:78:21: warning: operation on ‘t’ may be undefined [-Wsequence-point]
   return -c / 2 * ((--t) * (t - 2) - 1) + b;
                    ~^~~~
g++ -c -pipe -O3 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Iincludes -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ires/tmp -isystem /usr/include/libdrm -Isrc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o res/tmp/tempscheduler.o src/tempscheduler.cpp
In file included from src/tempscheduler.cpp:2:
src/ui_tempscheduler.h: In member function ‘void Ui_TempScheduler::setupUi(QDialog*)’:
src/ui_tempscheduler.h:194:24: error: ‘class QDoubleSpinBox’ has no member named ‘setStepType’; did you mean ‘setStyle’?
         doubleSpinBox->setStepType(QAbstractSpinBox::DefaultStepType);
                        ^~~~~~~~~~~
                        setStyle
src/ui_tempscheduler.h:194:54: error: ‘DefaultStepType’ is not a member of ‘QAbstractSpinBox’
         doubleSpinBox->setStepType(QAbstractSpinBox::DefaultStepType);
                                                      ^~~~~~~~~~~~~~~
make: *** [Makefile:560: res/tmp/tempscheduler.o] Error 1

```

**Comment by Fushko** [comment]
Qt version? You can tell by running `qmake --version`

**Comment by Fushko** [comment]
Closed for inactivity.

**Comment by datalot-369** [comment]
I don't know if my system has updated its Qt-packages from the creation of this issue, but it says:

```
$ qmake --version
QMake version 3.1
Using Qt version 5.11.3 in /usr/lib/x86_64-linux-gnu
```

Distro: `MX-19.2_x64`

PD: In my honest opinion, 6 days are very few days to close an issue. Inkscape (e.g.) limits it to two months _if there are no controversial topics_.

**Comment by datalot-369** [comment]
After trying re-installing all the [Linux packages requirements for Debian-based distros](https://github.com/Fushko/gammy#packages), `apt` said:

```
$ sudo apt install git build-essential libgl1-mesa-dev qt5-default libxxf86vm-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.6).
git is already the newest version (1:2.20.1-2+deb10u3).
libxxf86vm-dev is already the newest version (1:1.1.4-1+b2).
libgl1-mesa-dev is already the newest version (18.3.6-2+deb10u1).
qt5-default is already the newest version (5.11.3+dfsg1-1+deb10u3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

It's visible that `qt5-default` is `5.11.3+` (older than the `5.12+` required)

**Comment by Fushko** [comment]
Hi,

MX 19.1 doesn't provide Qt 5.12. 
Here: https://packages.ubuntu.com/focal/qt5-default you can downloated the latest .deb package (5.12.8).

I actually haven't tried this myself, so I'd appreciate if you could tell me whether that works for you. :)

> In my honest opinion, 6 days are very few days to close an issue

You're right. But I (rightly) assumed you were using an unsupported Qt version, given your distro version.

**Comment by datalot-369** [comment]
I strongly think this is so dangerous.
To be simple, `qt5-default (5.12.8+dfsg-0ubuntu1)` depends on `qtbase5-dev (= 5.12.8+dfsg-0ubuntu1)`.

Now, you can take a look at the [`qtbase5-dev mandatory dependencies`](https://packages.ubuntu.com/focal/qtbase5-dev) and see why I just can't try to do it by myself.

The two few-confident alternatives I can choose are the download of the full Qt environment (Like a `.zip`), or associate a Debian-compatible repository to update my Qt packages without risks.

I have seen this second is not possible with any of the available testing or stable repositories that MX Linux or Debian provides. Maybe Qt 5.12 is actually unstable.

- Is there a chance to change the Gammy codebase to be Debian-compatible? (The project is skipping a lot of distros this current way)
- How necessary is the inclusion of Qt 5.12 in the codebase? Gammy "Core" strongly depends on it?

**Comment by Fushko** [comment]
>I strongly think this is so dangerous.

I don't think it is, but it's your choice. :)

> Is there a chance to change the Gammy codebase to be Debian-compatible?

Not sure what you mean by that. It is Debian-compatible. I'm on a Debian-based distro myself. Your distro just doesn't have Qt 5.12.

> How necessary is the inclusion of Qt 5.12 in the codebase? Gammy "Core" strongly depends on it?

No, the core does not strongly depend on it. But don't expect it to be ported to something else anytime soon, at least not by me.

**Comment by datalot-369** [comment]
> Not sure what you mean by that. It is Debian-compatible. I'm on a Debian-based distro myself. Your distro just doesn't have Qt 5.12

I'm not speaking about (_based on the link you shared_) Ubuntu-based distros. Ubuntu is different in a lot of packaging-related topics.

> I have seen this second is **not possible with any of the** available **testing or stable repositories that** MX Linux or **Debian provides**.

I'm not a purist, but as this is close to change not just one package but a lot of dependencies: https://wiki.debian.org/DontBreakDebian

Closed as this is an upstream issue.
