### ISSUE TITLE
cannot install on 20.04

### ISSUE THREAD

**Issue by sapuizait** [Fushko/gammy#39]
Running Ubuntu 20.04 and Qt version is 5.6.2
Have installed all prerequisites but it will stubornly not get installed. Keep getting the error "PlaceholderText is not a member of QPalette" but my Qt is not < 5.1.2
As a workaround I deleted the offending lines (which were plenty) and run 'make' which did install it but then the package was broken "segmentation fault (core dumped)"
Any advice?

**Comment by bobrof** [comment]
Same problem with Debian 19/Qt 5.11.3
`g++ -c -pipe -O3 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Iincludes -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ires/tmp -isystem /usr/include/libdrm -Isrc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o res/tmp/mainwindow.o src/mainwindow.cpp
In file included from src/mainwindow.cpp:11:
src/ui_mainwindow.h: In member function ‘void Ui_MainWindow::setupUi(QMainWindow*)’:
src/ui_mainwindow.h:135:54: error: ‘PlaceholderText’ is not a member of ‘QPalette’
         palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush8);
                                                      ^~~~~~~~~~~~~~~
src/ui_mainwindow.h:151:56: error: ‘PlaceholderText’ is not a member of ‘QPalette’
         palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
                                                        ^~~~~~~~~~~~~~~
src/ui_mainwindow.h:169:56: error: ‘PlaceholderText’ is not a member of ‘QPalette’
         palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush8);
                                                        ^~~~~~~~~~~~~~~
`

**Comment by Fushko** [comment]
Both of those versions are older than **5.12** (not 5.1.2).
