### ISSUE TITLE
Multi-monitor support

### ISSUE THREAD

**Issue by Fushko** [Fushko/gammy#4]
The app was never tested on more than one monitor. This thread can be used to aggregate multi-monitor related issues.

**Comment by becquerel** [comment]
Thank you for great app. To help a little, I tested this on my workstation. I believe the app itself is running as expected (running three monitors, 2560x1440 + 3840x2160 + 2560x1440). I haven't tested on single monitor, but I would expect the same behavior I am experiencing.

Both auto and manual mode seem to work properly (aside from #5, but that is probably unrelated), I don't see any issues

As for multi-monitor support, I would ABSOLUTELY LOVE if there was a way to set up each monitor individually. I don't know whether this is even possible though. I often have dark-themed IDE on one screen and bright browser window on the other, so being able to control monitors separately would be absolute killer feature for this app.

Now, I am still going to use it, I find it very useful as it is.

**Comment by Fushko** [comment]
Thanks for the feedback. Good to know it works at least!

>As for multi-monitor support, I would ABSOLUTELY LOVE if there was a way to set up each monitor individually. I don't know whether this is even possible though. I often have dark-themed IDE on one screen and bright browser window on the other, so being able to control monitors separately would be absolute killer feature for this app.

That would be incredibly awesome if possible. I'd love to implement this if I ever get a multi-monitor setup going.

**Comment by becquerel** [comment]
> Thanks for the feedback. Good to know it works at least!
> 
> > As for multi-monitor support, I would ABSOLUTELY LOVE if there was a way to set up each monitor individually. I don't know whether this is even possible though. I often have dark-themed IDE on one screen and bright browser window on the other, so being able to control monitors separately would be absolute killer feature for this app.
> 
> That would be incredibly awesome if possible. I'd love to implement this if I ever get a multi-monitor setup going.

As much as I would love to help, I don't know much about C++ nor the technology behind the displays, so I would not be much of a help. But I am happy to help testing if nothing else

**Comment by logix2** [comment]
You could test 2 monitors in VirtualBox. In the machine settings you have the option of using multiple monitors.

**Comment by IncPlusPlus** [comment]
As a note, I just tried this on a multi-monitor setup on Pop!-OS 19.10 to no avail. I'm thinking it's probably because my monitors are connected using DisplayLink. Redshift seems to also suffer from this as noted in [jonls/redshift#311](https://github.com/jonls/redshift/issues/311). Unfortunately, it seems like [gamma correction isn't on the list of priorities for Linux](https://displaylink.org/forum/showthread.php?t=65641). [DisplayLink/evdi#44](https://github.com/DisplayLink/evdi/issues/44) exists for this purpose.

**Comment by divStar** [comment]
Hm so basically if I am on a multi-monitor set-up, it seems that even changing to e.g. just the "secondary" screen (WUHD monitor) does the job. If I turn on the second screen (laptop screen) back on, it stops working. Other than that it's a pretty nice app and works well if you only have one monitor at any given time.

**Comment by Fushko** [comment]
Closed as the multimonitor issues are a lot clearer.
