### ISSUE TITLE
Automatic color changes don't trigger when waking laptop from suspend

### ISSUE THREAD

**Issue by joelostblom** [Fushko/gammy#40]
Thanks for making gammy @Fushko ! I regularly switch between my laptop and an external monitor and gammy is the most convenient and robust solution I have found for adjusting both brightness and temperature on the fly (and I have tried many...). 

I have noticed a bug possibly related to #24. When my laptop wakes from suspend, gammy does not change the color temp although I have it set to automatically change based on time of day. So if I close my laptop at night when the color temp is low and then open it in the morning, gammy will not bring the temperature back up to the morning temp. If I uncheck and then recheck the "Auto" check box, gammy will  start changing the temperature as expected, so it seems like this event is working but not triggered properly on wake from suspend.

I am on Arch Linux Linux 5.6.15-arch1-1 and use i3 as my WM.

**Comment by Fushko** [comment]
It's definitely related to #24. Closing, thanks for the feedback.
