### ISSUE TITLE
Fatal error X11 - Invalid gamma ramp size

### ISSUE THREAD

**Issue by alexratencompass** [Fushko/gammy#41]
Ubuntu 18.04, gnome
build successfully, however on ./gammy launch receiving following error

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
2020-06-12 11:07:28.365 FATAL [6312] [X11::X11@65] Invalid gamma ramp size]

```

**Comment by Fushko** [comment]
Refer to the Troubleshooting section in the README.

**Comment by alexratencompass** [comment]
that didn't work, however seems like I am using wayland

**Comment by Fushko** [comment]
Closed as it's a wayland issue, which is not supported atm.
