### ISSUE TITLE
Compile error on Arch Linux:  stdint.h not included.

### ISSUE THREAD

**Issue by altcoinpirate** [Fushko/gammy#42]
When I attempt to compile on Arch Linux it gives the following error.

`src/utils.h:19:38: error: ‘uint8_t’ was not declared in this scope; did you mean ‘uid_t’?
`
Adding "`#include <stdint.h>`" to the src/utils.h file fixed the problem.

Thanks for all the hard work.

**Comment by AliTajelsir** [comment]
Any plans for the fix to be included officially?. Building from AUR fails unless the line is added manually.

**Comment by Fushko** [comment]
Should be fixed. However, you might not see it working on AUR until I add another tag (as far as I know).
