### ISSUE TITLE
Android Version?

### ISSUE THREAD

**Issue by rayman3003** [Fushko/gammy#43]
Is it possible for having an Android build of Gammy?

**Comment by Fushko** [comment]
Pretty sure Android has adaptive brightness built-in already.

**Comment by rayman3003** [comment]
> 
> 
> Pretty sure Android has adaptive brightness built-in already.

Adaptive brightness of android doesn't based on the temperature of the displaying screen, But the time & position of environment.

**Comment by Fushko** [comment]
Surely there must be a couple flux-like apps for that. I'm not going to make an Android version anytime soon, sorry :)
