### ISSUE TITLE
Allow installation into a custom prefix

### ISSUE THREAD

**Issue by Atemu** [Fushko/gammy#45]
Hi, I just packaged your project for Nix in https://github.com/NixOS/nixpkgs/pull/93029 and had to override the installPhase because `make install` always installs to /opt. It is usually expected to install into a directory specified by the `PREFIX` environment variable.

I imagine this would be an issue for most other software repos aswell, so it'd be better to fix it upstream.

**Comment by jtojnar** [comment]
For the record, here is an example of another qmake project that did that: https://github.com/corrados/jamulus/pull/247/files

**Comment by Fushko** [comment]
Added. Thanks @jtojnar for the suggestion.
Usage: `qmake Gammy.pro PREFIX=/custom/path/`
