### ISSUE TITLE
Setup resets itself after reboot

### ISSUE THREAD

**Issue by Translator5** [Fushko/gammy#46]
Info:
- Manjaro Linux
- v. 0.9.58-4
- installed trough AUR

Hi volks,

somewhy my settings for gammy reset itself after every first or second reboot - so that the temperature tick, the offset & speed settings go to default.

Do you have any idea how to fix this?
I installed it trough my user login not trough root.

**Comment by Fushko** [comment]
- The config path is /home/your_user/.config/gammy. Do you have it?
- Does this also happen when closing and reopening the app? Or just on reboot?

**Comment by Translator5** [comment]
Yes I do have the config file.
After closing gammy manually, whether just quit or quit and reset gamma does not reset the config file.
But after reboot-ing it is resetted.

**Comment by Fushko** [comment]
Can you rebuild the master branch with the latest changes and let me know if this still occurs? There are some config fixes.

**Comment by Translator5** [comment]
No did not work 😿

**Comment by Fushko** [comment]
Just had this happen to me. No clue how right now.

**Comment by stefanos82** [comment]
I'm facing this issue as well. It resets my settings when I reboot my computer.

```log
Distro: GNU / Linux Debian testing 64-bit fully updated
Kernel version: 5.8.0-1-amd64
```

**Comment by Fushko** [comment]
Can you guys check with 0.9.6? I fixed some potential config bugs. The file is now called to "gammyconf" by the way.

**Comment by stefanos82** [comment]
Now there's another peculiar behavior.

![image](https://user-images.githubusercontent.com/1777466/103446024-9a6a0c00-4c83-11eb-8bd4-8c3353592246.png)

The settings above are the ones I'm about to save; done, closing it, re-opening it.

![image](https://user-images.githubusercontent.com/1777466/103446037-c5ecf680-4c83-11eb-9d82-2b684392bf90.png)

What's with the -1 to Range's beginning?!

**Comment by stefanos82** [comment]
By the way, why not calling it `gammyconf.json`, much like VSCode is saving its settings?

Besides, you are saving JSON data, it makes more sense.

**Comment by Fushko** [comment]
> What's with the -1 to Range's beginning?!

No idea. Just noticed it on my end. I'll check it out.

> By the way, why not calling it gammyconf.json

For brevity. It's a little more convenient. Also extensions are mostly unnecessary on Unix.

**Comment by stefanos82** [comment]
Whatever it works then...

**Comment by Gitoffthelawn** [comment]
I can confirm @stefanos82's findings regarding the -1 of range after restart.  I also experienced a stuck temperature, but I need to spend more time to isolate that issue.

**Comment by Fushko** [comment]
> I can confirm @stefanos82's findings regarding the -1 of range after restart. I also experienced a stuck temperature, but I need to spend more time to isolate that issue.

Do you have it anymore? I think I fixed it.

**Comment by stefanos82** [comment]
No, it's still there.

**Comment by Gitoffthelawn** [comment]
I tested again in v0.9.6.1, and both the upper and lower bounds of the range decreased by 1 on restart.

**Comment by Fushko** [comment]
Fixed on 0.9.62. It was just a visual bug.

**Comment by stefanos82** [comment]
A kind suggestion if I may: before closing a ticket, please make sure you have the fix available in main repository so users can compile the latest commit and apply changes on their app.

When you merge `develop` in `master`, let me know.

**Comment by Fushko** [comment]
@stefanos82 it's out :+1:

**Comment by stefanos82** [comment]
Perfect; works as expected :+1:
