### ISSUE TITLE
How can I run Gammy without keeping its terminal tab open?

### ISSUE THREAD

**Issue by Mennaruuk** [Fushko/gammy#49]

**Comment by DuskTails** [comment]
Hi, I saw your title and remarked that I had the exact same problem, but I managed to solve it a few different ways. The first and easiest solution is when running gammy through the terminal, put nohup in front of whatever your using to launch gammy. This means that there will be no hang up (no sigterm/sigkill will be sent) to gammy after closing the terminal when it gives you the warning message. This gives you the ability to, despite the warning, close the terminal and still have gammy operating in the tray.

If however you want to automate gammy opening with Ubuntu on boot so you don't have to keep opening it yourself all the time, there are two solutions below, the first which I found online and didn't work for me, the second an extremely simple script I created to get it launched via Startup Applications. 
The first solution requires setting up a file in the ~/.config/autostart directory with a script that starts gammy. The second solution sets up a bash script that you set to open up with Startup Applications if you're on Ubuntu. For each solution, once you have saved the script, you must reboot to see if it will work and open gammy.

The script for the first solution is this.
Create it via the command: sudo nano /home/[user]/.config/autostart/gammy.desktop

[Desktop Entry]
Type=Application
Exec=/opt/gammy/bin/gammy
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Gammy adaptive screen brightness

If the above doesn't work, the script for the second solution is this.
Create is via the command (make sure you're in ~): sudo nano gammy_wakeup.sh

#!/bin/bash
/home/[user]/gammy/gammy

The above assumes you compiled gammy from source. Then simply open up Startup Applications and after clicking Add, state the full path to gammy_wakeup.sh in the command box via: /home/[user]/gammy_wakeup.sh
Alternatively you can not worry about making a script whatsoever and just outright state the path to gammy directly in the command box without using the script by using the same line you put in it. Sometimes I had issues with this though so although it appears redundant, I decided to settle with the script instead.

Hope this helped! I've been using Linux for only a little over a week myself so apologies in advance for any mistakes.

**Comment by Fushko** [comment]
Run the following on gammy's folder:
`sudo make install`
Now, press Alt+F2 to bring up the command prompt, then type `gammy`. That's what I do. 

(I should probably put this in the readme, apologies)

**Comment by Mennaruuk** [comment]
@Fushko I attempted entering `gammy` in terminal after running `sudo make install` on gammy's folder. Unfortunately, it tells me,
`bash: gammy: command not found`. Running on Solus 4.1.

I followed @DuskTails' first suggestion and now the app works without terminal. (On Solus, it's different: I had to go to terminal and type `cd /usr/share/applications`, then `sudo nano gammy.desktop`, and enter the information provided by @DuskTails as well as enter the correct Gammy directory.) I had to install GNOME Tweaks to add it as a startup application. What worries me though is that now that it's a .desktop file, every time I click on Gammy, it spawns a new instance.
![image](https://user-images.githubusercontent.com/52135169/100190587-9399ed80-2ebc-11eb-878a-0ad0df05a550.png)

Also, for anyone struggling to install Gammy on Solus, you will need these four packages. You can find them in the Software Center.

qt5-base-devel ([required for qmake](https://asksolus.com/254/qt-creator-qmake-missing-in-solus?show=255#a255))
system.devel ([required as an equivalent of build-essential](https://stackoverflow.com/a/37528215))
libx11-devel ([required to solve the fatal error: 'X11/Xlib.h' file not found](https://www.reddit.com/r/freebsd/comments/60756a/installing_the_x11_developer_library/?utm_source=share&utm_medium=web2x&context=3))
libxxf86vm-devel ([required to solve the fatal error: X11/extensions/xf86vmode.h: No such file or directory](https://zoomadmin.com/HowToInstall/UbuntuPackage/libxxf86vm-dev))

Thanks @Fushko and @DuskTails for your guys' help!

**Comment by DuskTails** [comment]
@Mennaruuk Hmm, so if I'm understanding this correctly, you're using the script from the first solution with the startup application method of the second solution? I think because they both use slightly different methods of starting up that it's causing a duplication problem, though I'm not experienced enough to know for sure. Maybe run a bash script similar to the second solution but for your particular directory in Solus and have that be the one that the startup application chooses, instead of the .desktop one from the first solution. Or even try making a startup application file where the command you insert is simply a path to the gammy file itself if it decides to work on your setup.

**Comment by Fushko** [comment]
> @Fushko I attempted entering `gammy` in terminal after running `sudo make install` on gammy's folder. Unfortunately, it tells me,
> `bash: gammy: command not found`. Running on Solus 4.1.

My bad, you also need to to make a symbolic link for it to work:
`sudo ln -s /usr/opt/bin/gammy /usr/local/bin/`

**Comment by Mennaruuk** [comment]
@DuskTails You are correct. I don't know, I just like having the program show up when I search for it. But it does run during startup. And I rarely shutdown my computer, so it shouldn't be an issue.

@Fushko Yeah, Solus isn't recognizing `/usr/local/bin/`. I don't think it exists as part of the Solus system. I'm trying to figure out another way to create this symbolic link. I did find gammy file in `/usr/opt/bin/`, but even after deleting that file and creating a new symbolic link to that folder, gammy doesn't work when entering it in terminal.

**Comment by Fushko** [comment]
The default path of `sudo make install` is now /usr/local/bin. In most distros, that path is in the $PATH variable, which means you can just run the command `gammy` from anywhere (terminal, command prompt). Weird that Solus doesn't have it though.

**Comment by Mennaruuk** [comment]
Thank you!
