### ISSUE TITLE
Brightness is lower than default even on max brightness

### ISSUE THREAD

**Issue by Fushko** [Fushko/gammy#5]
Brightness may result lower than usual even when set to max. This happens on my laptop.

Running `xrandr --verbose | grep -i brightness` reports the same brightness, even when lowering it. Gamma readings also remain unchanged when modifying temperature, even though temperature gets visibly changed.

A workaround for now is to offset the brightness through xrandr, for instance:
`xrandr --output eDP --brightness 1.2`

To find out the output: `xrandr --listmonitors`

**Comment by becquerel** [comment]
confirmed on my end, running Ubuntu 18.04 / 5.2.8-050208-generic

**Comment by Fushko** [comment]
It appears that 100% brightness equals 50% brightness in some cases. I added a button that allows the maximum brightness to go up to 200% to work around this. Changes are on develop branch.

**Comment by Fushko** [comment]
Just pushed a slightly hacky fix on develop. Works on my laptop and desktop but I don't know if it covers all cases. Feedback appreciated :+1:

**Comment by Fushko** [comment]
Should be fixed for good now.
