### ISSUE TITLE
Is there a way to change brightness only?

### ISSUE THREAD

**Issue by Mennaruuk** [Fushko/gammy#50]
I use Redshift, and I don't want Gammy to affect the temperature of my screen. How can I do that? I unchecked the Auto button next to Temperature, but I wanna disable Temperature in the first place and only keep the dimming effect.

**Comment by Fushko** [comment]
You can't use both Redshift and Gammy together, even if you only have auto-brightness on Gammy. 
Right now, Gammy changes pixel values to achieve the dimming effect. Redshift does it too with temperature, so the two apps can't work together unfortunately.
If and when Gammy provides backlight brightness dimming (on monitors that support it), using both will be possible.

**Comment by Mennaruuk** [comment]
I can assume that Gammy also won't work with system features like [Night Light in Solus](https://averagelinuxuser.com/assets/images/posts/2019-04-26-after-installing-solus/Solus_After_installing_NightLight-800x573.jpeg)? Thank you for your help!

**Comment by Fushko** [comment]
Nope, you'd run into the same problem.

**Comment by Mennaruuk** [comment]
No problem, thank you!
