### ISSUE TITLE
Playing media resets to pure gamma

### ISSUE THREAD

**Issue by DuskTails** [Fushko/gammy#51]
Hi there,

Firstly thanks so much for maintaining this tool, it's the only brightness tool with proper settings that I've found that's still kept up to date for Linux and I am very grateful for your hard work.

One bug I'd like to report however is in regards to the title. For the first time on boot, when media (e.g. a video from YouTube being played on Firefox, music being played in default music application on Ububntu 20.04.1 LTS) is played, upon clicking the play button the brightness setting on Gammy gets reset to pure gamma. Fixing it requires toggling the little window from tray and adjusting the brightness slider by some increment. Note that this only happens for the first time it's played on boot. Also note that it can happen once when playing a YouTube video in Firefox, and then again when playing a song through music player, but only once each for the first time on boot (hope that's clear). My memory is foggy but I think I even saw one instance of it happening again even after media has been played for the first time on boot, but that might just be my memory being off.

Not a critical problem but I thought it'd be good to make you aware of it in case you wish to look into it in the future. My thanks again for your work on Gammy!

**Comment by Fushko** [comment]
Hello, thanks for the kind words.

I experience this issue too. There is probably a way to detect a gamma change by another app and react accordingly. I just found out, the Nvidia settings app is able to detect it and show a warning when it's changed by Gammy. I'll look into it!

**Comment by Fushko** [comment]
As there is no headache-free way of determining if some other app changed the color palette (that I know of), I'll just reapply my app's settings every 5 seconds.

**Comment by Fushko** [comment]
Process described above is in 0.9.6.
