### ISSUE TITLE
Increase max Adaptation speed limit

### ISSUE THREAD

**Issue by maciejmotyka** [Fushko/gammy#52]
Currently, the user can specify "Adaptation speed" up to 60 minutes. I'd like to set this to 120 min or probably even higher. The limit for the UI element is set here: https://github.com/Fushko/gammy/blob/19c2625ec36c894ebfe4ec5baff507d76f5dc713/src/tempscheduler.ui#L349.
Do you expect any troubles if this is changed and "Adaptation speed" is set to more than 60 minutes?

**Comment by Fushko** [comment]
There shouldn't be any trouble at all. I'll definitely increase the limit in the future.

**Comment by Fushko** [comment]
Increased to 3 hours. Let me know if you need higher.
