### ISSUE TITLE
Expose command line interface?

### ISSUE THREAD

**Issue by dave-epstein** [Fushko/gammy#56]
Hi,

Thanks so much for putting together this program. It's a life saver in terms of having "Night Light"-esque behavior with changing screen brightness too. I was wondering how easy/doable it would be to expose a command line interface (mostly since this would in turn allow the configuration of keyboard shortcuts), to set/increase/decrease brightness and temperature, as if it were being done from the GUI.

Would highly appreciate you considering this option, but I will keep dragging those sliders if need be :) 

Thanks again!

**Comment by Fushko** [comment]
Hey, glad you found it useful.
I don't know much about CLI programming, but I suppose it's not too hard to implement set / increase / decrease commands. 
I'll see.

**Comment by igalic** [comment]
you could use dbus as communication interface to send those commands to the running instance, and otherwise just do it directly, if there is no running instance, do it directly
this gets tricky when there is no dbus

**Comment by yassinebridi** [comment]
This would be really useful, it would give so much flexibility to the users.

**Comment by mi544** [comment]
I was about to suggest the same.
It's a really useful feature that I'm missing. Implementing it would help users who want to have full control over setting screen temperature.  

Right now, the `Auto` setting doesn't work good well on my computer for both screen brightness and screen temperature. While this is an issue for another ticket, having command line interface would have allowed me to create a simple bash script that would check current time and set screen temperature immediately with a command. Then I could run it every minute or so, and that would be a temporary fix for another issue.  

Having arguments you can pass to the program would also allow for extensibility and extensive use in other types of scripts and programs. I could write a simple script that would change screen temperature based on music I'm playing, certain specific sensors around the house, etc.  

Finally, I start my `gammy` instance in an auto-start script, and allowing to specify if I want `Auto` modes enabled or disabled on start would be great.  

Really anything programmatic requires command line interface and I think a lot of people could benefit from it.  

This is what a potential user interface could look like (extending the majority of functionality as command line arguments):
```
gammy [OPTION]...

OPTIONS
  -b, --brightness=PERCENTAGE
         Set current brightness to PERCENTAGE. The PERCENTAGE is specified in range of `0` to `200`

  -t, --temperature=TEMPERATURE
         Set current screen temperature to TEMPERATURE. TEMPERATURE is specified in Kelvins in range of `2000` to `6500`

  -bm, --brightness-mode=STATE
         Set current STATE of brightness mode. STATE can be `auto` or `manual`

  -tm, --temperature-mode=STATE
         Set current STATE of temperature mode. STATE can be `auto` or `manual`

  --sunrise-time=TIME
         Set TIME of sunrise. TIME is specified in 24-hr format, for example `05:32` or `13:00`

  --sunset-time=TIME
         Set TIME of sunset. TIME is specified in 24-hr format, for example `18:55` or `21:04`

  --sunrise-temperature=TEMP
         Set screen TEMPERATURE to be automatically set on sunrise. TEMPERATURE is specified in Kelvins in range of `2000` to `6500`

  --sunset-temperature=TEMP
         Set screen TEMPERATURE to be automatically set on sunset. TEMPERATURE is specified in Kelvins in range of `2000` to `6500`

  --adaptation-time=TIME
         Set screen temperature adaptation time. TIME is speficied in minutes, for example `0.5` for 30 seconds, `20` for 20 minutes, `120` for 2 hours

  --r, --reset
         Reset all gammy settings to their default state
```

I omitted all brightness settings here. It would of course be ideal to expose as many settings to command line as possible, but I think this is a fair starting point and more options can be added later.  

I can help write any documentation for that feature, including man pages, and help with overall design if needed.

Thank you.

**Comment by Fushko** [comment]
Hi @mi544, thanks for the writeup. I appreciate the pointers on how the interface could look like.

I would love to sort this out. However, I don't think it's wise to implement a CLI before making the app multi-screen aware, since the latter requires a substantial rewrite of the existing codebase.

Unfortunately I don't have as much time as I used to at the moment. Hopefully in the future I can pick up the pace again.

**Comment by Fushko** [comment]
CLI version is in development here: https://github.com/Fushko/gummy
