### ISSUE TITLE
Brightness offset should take into account max brightness

### ISSUE THREAD

**Issue by ronilaukkarinen** [Fushko/gammy#61]
Right now when I change max brightness to 80% which is preferred for me, adaptive features disappear. They should adjust accordingly, so when max is 100% and brightness is set up to 84% on white background, shouldn't with max 80% the auto brightness be around 64%? Now it caps at max which is 80%.

**Comment by Fushko** [comment]
That's what the offset slider is for. I should probably allow a negative offset to make what you say easier to accomplish.

**Comment by ronilaukkarinen** [comment]
Oh right. Didn't really understand the meaning of "offset". I'd prefer it to be fully automatic based on min and max values, that should be enough.

**Comment by Fushko** [comment]
You're right, offset should take into account max brightness. I'll do that for the next release.

**Comment by Fushko** [comment]
Added in 0.9.61
