### ISSUE TITLE
Increase Adaptation speed limit

### ISSUE THREAD

**Issue by truefriend-cz** [Fushko/gammy#62]
Hello,
Do you can Increase Adaptation speed to 0 second?
If am changing config file manually (param: speed) and open program then not functional ok.

**Comment by Fushko** [comment]
By 0 seconds, you mean super fast like 0.1, or literally instant, without a transition at all?

**Comment by truefriend-cz** [comment]
transition all to off

This is my manually settings:
```
{
    "auto_br": true,
    "auto_temp": false,
    "brightness": 500,
    "brt_fps": 300,
    "extend_br": false,
    "log_lvl": 3,
    "max_br": 500,
    "min_br": 348,
    "offset": 77,
    "polling_rate": 1,
    "speed": 0.001,
    "temp_fps": 45,
    "temp_high": 6500,
    "temp_low": 3400,
    "temp_speed": 30.0,
    "temp_state": 0,
    "temp_step": 0,
    "threshold": 1,
    "time_end": "06:00:00",
    "time_start": "17:00:00"
}
```
which is sufficient just when switching windows is to know the flicker before analyzing the contents of the screen (briefly displays white in full light, as when taking pictures with a flash camera).

However, this causes a problem in that the GUI interface also displays other parameters in meaningless values. Even on unchanged items.

When I change a single transition speed parameter to 0.1, the other items in the GUI also drop.

**Comment by Gitoffthelawn** [comment]
I would love to see the minimum allowed adaptation speed to be under 1 second.  Unlike the OP, I'm not too interested in 0 seconds, but something like 0.2-0.3 seconds would probably work well for me.

If you would prefer a separate issue report for this request, please just ask.

**Comment by Fushko** [comment]
> which is sufficient just when switching windows is to know the flicker before analyzing the contents of the screen

Depending on your system, you're going to see the full brightness instant regardless of how low you go with these settings. Even assuming adaptation speed and screenshot rate to 0 ms, the CPU still needs time to calculate the brightness, and then perform the animation.

On my main system with a Ryzen 5 2600, a screenshot rate of 50 ms and adaptation speed of 1 s results in virtually instant transitions. But the same settings may look much slower on a weaker PC.

On 0.9.60, I included some CPU optimizations when calculating brightness that may help. Please do try that if you haven't already.

Also, if you guys are on Windows, the app starts at below normal priority, which might make things worse. I'm going to remove it in a future release.

**Comment by Fushko** [comment]
> I would love to see the minimum allowed adaptation speed to be under 1 second. Unlike the OP, I'm not too interested in 0 seconds, but something like 0.2-0.3 seconds would probably work well for me.

I could probably go lower, yes. The limits are there to avoid lag, but I can lower them further.

**Comment by Gitoffthelawn** [comment]
> I could probably go lower, yes. The limits are there to avoid lag, but I can lower them further.

Interesting.  Is "adaptation" the time it takes to transition the display to a new gamma?  If so, it seems like a faster speed might actually reduce lag.  Especially if the transition is performed in fewer steps.  What are your thoughts?

Personally, for an advanced tool like Gammy, I prefer having no restrictions, and allow the user to find what works best for them in their specific environment.

**Comment by Fushko** [comment]
> faster speed might actually reduce lag

A faster adaptation speed, yes, marginally, because you are performing less iterations to get to the target brightness. So it can be lowered easily.
I was referring to the screenshot rate, which at 1 ms is very CPU intensive. But I'll lower its limit too.

Depending on your system, even at 0 ms and no adaptation you're still going to see a tiny fraction of a second where the screen is at full brightness, because of the overhead of taking the screenshot, calculating brightness, filling the gamma array and applying it.

**Comment by truefriend-cz** [comment]
> > faster speed might actually reduce lag
> 
> A faster adaptation speed, yes, marginally, because you are performing less iterations to get to the target brightness. So it can be lowered easily.
> I was referring to the screenshot rate, which at 1 ms is very CPU intensive. But I'll lower its limit too.
> 
> Depending on your system, even at 0 ms and no adaptation you're still going to see a tiny fraction of a second where the screen is at full brightness, because of the overhead of taking the screenshot, calculating brightness, filling the gamma array and applying it.

And wouldn't it be possible to use this function to work inversely? That by default the brightness value would be the lowest and would gradually increase according to the measured value? To eliminate those micro-time flashes.

**Comment by Gitoffthelawn** [comment]
> I was referring to the screenshot rate, which at 1 ms is very CPU intensive. But I'll lower its limit too.

I noticed that the v0.9.6 release has a screenshot rate ***maximum*** of 500ms, whereas I think previous versions had a ***minimum*** of 1000ms.  I have a hunch this is a bug.

**Comment by Fushko** [comment]
> > I was referring to the screenshot rate, which at 1 ms is very CPU intensive. But I'll lower its limit too.
> 
> I noticed that the v0.9.6 release has a screenshot rate _**maximum**_ of 500ms, whereas I think previous versions had a _**minimum**_ of 1000ms. I have a hunch this is a bug in the current release.

No, Windows 7 had different minimum and maximum because the screenshot method used there causes screen stutters. I removed it, now it's in line with all other OSes.

**Comment by Fushko** [comment]
Changes discussed are in 0.9.60

**Comment by truefriend-cz** [comment]
Thnak you very much.
