### ISSUE TITLE
0.9.59 > 0.9.6

### ISSUE THREAD

**Issue by yochananmarqos** [Fushko/gammy#63]
Shouldn't the new version be 0.9.60?

**Comment by Fushko** [comment]
The way I see it, 9.59 < 9.6. But I realize that's probably not standard, since github places it under 0.9.41. How problematic is this?

**Comment by yochananmarqos** [comment]
I'm the AUR package maintainer. I would rather not use an [epoch](https://wiki.archlinux.org/index.php/PKGBUILD#epoch) to provide users with a new version.

```
❯ vercmp 0.9.59-1 0.9.6-1
1
❯ vercmp 0.9.59-1 0.9.60-1
-1
```

```
Output values:
  < 0 : if ver1 < ver2
    0 : if ver1 == ver2
  > 0 : if ver1 > ver2
```

**Comment by Fushko** [comment]
Ok, check now.

**Comment by yochananmarqos** [comment]
That works for the stable release, but the VCS package isn't pulling the new tag for some reason. 

```
printf "%s" "$(git describe --long --tags | sed 's/^v//;s/\([^-]*-\)g/r\1/;s/-/./g')"
```
```
0.9.6.r0.8a65ae6-1
```

**Comment by yochananmarqos** [comment]
That works for the stable release using the tarball, but the VCS package still pulls the old tag for some reason:

```
git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
```
```
0.9.6.r0.g8a65ae6
```

**Comment by Fushko** [comment]
Deleted it altogether. What about now?

**Comment by yochananmarqos** [comment]
That did the trick, thanks. 

```
0.9.60.r0.g8a65ae6-1
```

**Comment by Fushko** [comment]
Great. Thanks for maintaining the AUR package, appreciate it!
