### ISSUE TITLE
Version not incremented for v0.9.6.1

### ISSUE THREAD

**Issue by Gitoffthelawn** [Fushko/gammy#67]
Just FYI, v0.9.6.1 release still indicates v0.9.6.0 within the executable's details (but is correct in the system tray menu).

Also gammylog.txt was released with it, which probably was accidental.

**Comment by Fushko** [comment]
I tend to update the windows version once every major version. The real one is seen in the tray.

> Also gammylog.txt was released with it, which probably was accidental.

Whoops.

**Comment by Gitoffthelawn** [comment]
Sounds good.  I'm a big advocate of incrementing version numbers whenever anything changes.

Closing this now... if for any reason you see a need to re-open, go for it! :)
