### ISSUE TITLE
Remember window position

### ISSUE THREAD

**Issue by Gitoffthelawn** [Fushko/gammy#68]
Pressing the ellipses (3 horizontal dots) next to the top "Auto" checkbox causes the UI to expand below the visible screen area.  Thus, after pressing that UI element, the user always has to move the Gammy window to a new position to see the expanded area.

Tested with v0.9.6.1 on Win7.

**Comment by Fushko** [comment]
I'll implement saving the window position, so that you only have to move it once.

**Comment by Gitoffthelawn** [comment]
I think those are both great ideas.

There's also the matter of the Gammy window being always-on-top.  I've gone back and forth on whether or not I think that's best.  It's definitely different; at least for me, being always-on-top matches what I want at least 75% of the time.  Often different is good. :)

**Comment by Fushko** [comment]
Added on 0.9.63. Also the window starts at the center of the screen now.

**Comment by Gitoffthelawn** [comment]
@Fushko Thanks for the update!

I haven't tried the new code yet, so some of my comments/questions below may not be relevant.

Did you add saving the window position in Gammy's configuration file?

I do think opening just above/below the system tray works well, and is what the user expects.  I have a hunch you'll get complaints about opening it in the center of the screen, as there will be more pointer movement required.

Would it be possible for it to keep the same position as before, but just shift up/down when expanded/contracted?

If that involves too much work, what do you think of just showing it expanded and not have it expand/contract?

**Comment by Fushko** [comment]
> Did you add saving the window position in Gammy's configuration file?

Yes.

> I do think opening just above/below the system tray works well, and is what the user expects. I have a hunch you'll get complaints about opening it in the center of the screen, as there will be more pointer movement required.

Some people have the system tray on top, some on the bottom. Some on the left, some on the right. Figuring out the optimal position for each case is difficult and not worth it. Not a huge issue, because you are able to move it and keep it where you want now.

> Would it be possible for it to keep the same position as before, but just shift up/down when expanded/contracted?

Yes, but I'm okay with how it is now.

> what do you think of just showing it expanded and not have it expand/contract?

I was thinking that maybe I should still show the range and offset sliders when auto brightness is off, but have them greyed out. Still undecided though. I like keeping only the bare necessary on the window.

**Comment by Gitoffthelawn** [comment]
> Yes.

Great!

> Some people have the system tray on top, some on the bottom. Some on the left, some on the right. Figuring out the optimal position for each case is difficult and not worth it. Not a huge issue, because you are able to move it and keep it where you want now.

Yup.

> Yes, but I'm okay with how it is now.

I look forward to trying the new version whenever you have time to release it. 

> I was thinking that maybe I should still show the range and offset sliders when auto brightness is off, but have them greyed out. Still undecided though. I like keeping only the bare necessary on the window.

I go back and forth in my mind too.  I like the minimalist approach, but I also find the expanding/contracting to be a bit cumbersome and it obviously adds an extra step.

Does the new release remember if the UI was previously expanded?  That could potentially be a good compromise.

**Comment by Fushko** [comment]
> Does the new release remember if the UI was previously expanded?

It does when auto brightness is on but it's always the same fixed size.

> I look forward to trying the new version whenever you have time to release it.

Here's a pre-release: [gammy_v0.9.63-pre.zip](https://github.com/Fushko/gammy/files/5861267/gammy_v0.9.63-pre.zip). Feedback welcome as always.

Apart from the UI changes, the window now starts maximized the first time. Also, there's two new system tray items for toggling brightness and temp.

**Comment by Fushko** [comment]
Added on 0.9.63
