### ISSUE TITLE
Middle click on icon to toggle on/off?

### ISSUE THREAD

**Issue by mxmilkiib** [Fushko/gammy#73]

**Comment by Gitoffthelawn** [comment]
I really like this idea.  A context menuitem for Gammy's tray icon to toggle it on/off would also be nice.

**Comment by Fushko** [comment]
Added on develop. It works this way:
if any of the auto checkboxes are on, disable everything. Otherwise, enable everything.
If you don't want to enable everything, there are two new tray menu items that let you check only one Auto box at a time.

**Comment by Fushko** [comment]
Added on 0.9.63
