### ISSUE TITLE
Can't start on windows

### ISSUE THREAD

**Issue by Eikosa** [Fushko/gammy#85]
![image](https://user-images.githubusercontent.com/20538090/105777731-f3277e80-5f7b-11eb-8ed4-edce8e3219ef.png)

when i open the program i get this error and it won't open

**Comment by Fushko** [comment]
Please try this: 
[gammy_v0.9.63.zip](https://github.com/Fushko/gammy/files/5870202/gammy_v0.9.63.zip)

**Comment by Eikosa** [comment]
awesome, thank you :)
