### ISSUE TITLE
Handling all 3 cases of clicking on the system tray icon

### ISSUE THREAD

**Issue by Gitoffthelawn** [Fushko/gammy#86]
Wow, you've done an amazing job with v0.9.63!  Thank you!

When clicking Gammy's system tray icon, there are 3 possible cases:

1. Gammy's UI was not open when the icon was clicked.  v0.9.63 (and previous versions) handles this case correctly by opening the UI.
2. Gammy's UI is already visible and is the foreground window.  In this case, pressing Gammy's system tray icon should close Gammy's UI.  v0.9.63 does *not* do this.
3. Gammy's UI is open, but is not the foreground window.  There are 2 ways to handle this: (A) bring Gammy's UI to the foreground, or (B) close Gammy's UI.  Different system tray apps handle this case differently.  Currently, Gammy 0.9.63 does neither A, nor B, so it would be good to perform one or the other.

**Comment by Fushko** [comment]
These are all good ideas. Regarding 3, I'd much rather do B (i.e. point 2), as I've already tried A before and it was troublesome.

**Comment by Gitoffthelawn** [comment]
> These are all good ideas. Regarding 3, I'd much rather do B (i.e. point 2), as I've already tried A before and it was troublesome.

I'm glad you like! :)

Regarding 3, both behaviour A and B are commonly implemented, and I find little consistency in the real world.

The CopyQ project (https://github.com/hluk/CopyQ) currently uses B for its behaviour.  Sometimes I find that behaviour desirable, and other times I find it unwanted.  I haven't performed a full UX analysis of which behaviour is desirable more often, nor mapping out all the negative ramifications of an application performing the undesirable behaviour.   So given that you mention that behavior B is easier to implement, I think it's fair to at least start with that approach.

**Comment by Fushko** [comment]
Added in 0.9.64. It acts exactly as *Show/Hide Gammy* in the tray menu.

**Comment by Gitoffthelawn** [comment]
@Fushko Thanks.  I'm hoping to have time to try 0.9.64 very soon.  I noticed that in 0.9.63, clicking on the system tray icon would often open Gammy ***behind*** other windows.  Is this fixed in 0.9.64, or would you like me to write up an issue report for you to track?

**Comment by Fushko** [comment]
> Is this fixed in 0.9.64, or would you like me to write up an issue report for you to track?

This is not fixed, or rather, it's not a bug, it's standard windows behaviour. Opening a window is not the same as giving it focus.
As I said, I tried to implement this a while ago and it didn't work well. But maybe I'll give it another shot at some point, so feel free to open up a new issue.

**Comment by Gitoffthelawn** [comment]
Sounds good... will do.
