### ISSUE TITLE
Floating dialog window type?

### ISSUE THREAD

**Issue by mxmilkiib** [Fushko/gammy#88]
Gammy now starts with the options dialog open as a standard window. Could giving it a dialog hint be possible? https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm45623487848608

**Comment by Fushko** [comment]
It was a dialog previously. I removed it because I didn't find it useful. Why do you want it back?

**Comment by mxmilkiib** [comment]
It being a dialog means that tiling window managers like [Awesome](https://awesomewm.org) will automatically float the window, instead of tile it. If it's too much to ask, I (and others) can add a config line to automate floating it.

**Comment by Fushko** [comment]
I see. It's true that in most cases you want the window for a program like this to float. However, as you pointed out, any decent tiling WM allows to force floating mode. Perhaps I'll add an option in the future, but I'm okay with it right now.
