### ISSUE TITLE
AUR package?

### ISSUE THREAD

**Issue by tiotrom** [Fushko/gammy#9]
It would be great to also have an AUR package :) - perhaps the biggest Linux repository :D

**Comment by Fushko** [comment]
There is: https://aur.archlinux.org/packages/gammy-git/

However it’s using 0.9.42 which is obsolete now.

**Comment by tiotrom** [comment]
Ah thank you! I will report as being out of date!

**Comment by parkerlreed** [comment]
It's git. It will always pull latest. The pkgver there is meaningless

**Comment by Fushko** [comment]
That’s great, didn’t know. Guess I can close this.

**Comment by yochananmarqos** [comment]
@Fushko 
I'm the AUR maintainer of [`gammy-git`](https://aur.archlinux.org/packages/gammy/). I'm not sure why the `pkgver` array still generates 0.9.42 even though the latest tag is 0.9.47.

@tiotrom I just added the stable version: [`gammy`](https://aur.archlinux.org/packages/gammy/).

**Comment by parkerlreed** [comment]
@yochananmarqos VCS (git) pkgbuilds should have a pkgver function that pulls in the latest tag or commit hash from git. There's a few methods you can use for this.

https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git

**Comment by parkerlreed** [comment]
Your git package is stil pulling the tar.gz heh. You want to use git for the git package and just pull master. That may be why pkgver was generating weird
