### ISSUE TITLE
Support DDC/CI

### ISSUE THREAD

**Issue by mirh** [Fushko/gammy#99]
It would be enormously better for eyes, if you actually lowered down brightness/contrast ***in*** the monitor, rather than using the current faux darkness overlay.

**Comment by Fushko** [comment]
Backlight support is planned. I thought that mentioning it two times in the README was enough.

**Comment by mirh** [comment]
Backlight is usually implemented through ACPI, gpu registers, or whatever other platform-specific shenanigan. 
DDC is another thing, so much so that (depending on the monitor) you might set gamma directly on the hardware.

**Comment by Fushko** [comment]
> Backlight is usually implemented through ACPI, gpu registers, or whatever other platform-specific shenanigan.

Can't you also control backlight brightness through DDC/CI? That's what I was planning to use already.

> DDC is another thing, so much so that (depending on the monitor) you might set gamma directly on the hardware.

Just to be clear, are you asking for DDC/CI support for everything, including pixel brightness? It would still be a "faux darkness overlay" in that case, just in the monitor.

**Comment by mirh** [comment]
> Can't you also control backlight brightness through DDC/CI? 

Uh, yes, right.. even though I'd usually just call it brightness on external monitors
I thought you were just talking about embedded displays. 

> Just to be clear, are you asking for DDC/CI support for everything, including pixel brightness?

Maybe there's a language barrier (non penso) but last time I checked "brightness" in monitors has actually always meant the backlight. 

On the other hand, I guess like pixel contrast (which is what I currently tinker with on my 27GN850 to further decrease.. perceived luminance) may not be different from faux darkness. But I'm not 100% sure.

**Comment by Fushko** [comment]
> I thought you were just talking about embedded displays.

All LCDs have a backlight, embedded or not. The same concept applies.

> Maybe there's a language barrier (non penso) but last time I checked "brightness" in monitors has actually always meant the backlight.

There's pixel brightness, and there's backlight brightness. Usually, the distinction is not made, i.e. there's just one "Brightness" slider that controls the backlight. Some screens (usually TVs) allow you to change both however.

My app currently allows you to just change pixel brightness, which I realize is far from ideal.

> On the other hand, I guess like pixel contrast (which is what I currently tinker with on my 27GN850 to further decrease.. perceived luminance) may not be different from faux darkness. But I'm not 100% sure.

Well, if we go by the assumption that changing RGB values rather than the backlight is a fake adjustment, then yes, it would fit that definition.

**Comment by mirh** [comment]
> All LCDs have a backlight, embedded or not. The same concept applies.

I know, but in normal parlance people seem to distinguish terms. 

> Some screens (usually TVs) allow you to change both however.

Right, good point. Fair is fair. 
It seems like this could also probably apply to professional-grade equipment too. 

> Well, if we go by the assumption that changing RGB values rather than the backlight is a fake adjustment, then yes, it would fit that definition.

You are right (and I have in fact just tested this), but somehow not quite either
https://doc.lagout.org/science/0_Computer%20Science/2_Algorithms/Digital%20Video%20and%20HD_%20Algorithms%20and%20Interfaces%20(2nd%20ed.)%20[Poynton%202012-02-07].pdf#page=88
